### PR TITLE
Check for snapshot existence before delete

### LINKED ISSUE #539: Repository overwrite for different workload with same name in different namespace
**Problem:**
If we have two different workload with same name in different namespace and they use same bucket to store backup snapshot then repository in the bucket overwrite each other.
**Reason:**
Namespace is not used in `HostNamePrefix`.
https://github.com/appscode/stash/blob/cee03417cf5f8becf78a6baef64e4e94829e89f2/apis/stash/v1alpha1/workload.go#L65

### LINKED ISSUE #549: Delete snapshot command does not check for snapshot's existence
**Observed behaviour:**
When we delete a Snapshot with `kubectl delete <snapshot-name>` command, it show delete successful even if the snapshot does not exist.

For example
```
$ kubectl delete snapshot default.deployment.stash-demo-36fs0b4b
snapshot.repositories.stash.appscode.com "default.deployment.stash-demo-36fs0b4b" deleted

$ kubectl delete snapshot default.deployment.stash-demo-36fs0b4b
snapshot.repositories.stash.appscode.com "default.deployment.stash-demo-36fs0b4b" deleted
```
In the first command we delete a snapshot and it success. In second command we try to delete the snapshot again. This time it also success even if the snasphot does not exist.

**Expected behaviour:**
API server should throw an error showing snapshot not found.

**Reason:**
Snapshot's existence was not checked in `Delete` method for snapshot.

### PR DESCRIPTION
**Pull request by hossainemruz**
This PR fixes #549
Task list:
- [x] Check if snapshot exist before delete
- [x] Used `k8s.io/apimachinery/pkg/api/errors`

### CODE REVIEW

File: hack/docker/setup.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ source "$REPO_ROOT/hack/libbuild/common/public_image.sh"
 
 APPSCODE_ENV=${APPSCODE_ENV:-dev}
 IMG=stash
-RESTIC_VER=${RESTIC_VER:-0.9.1}
+RESTIC_VER=${RESTIC_VER:-0.8.3}
```
Comment (tamalsaha) [inline hack/docker/setup.sh]: Reverts back to 0.8.3 because of https://github.com/restic/restic/issues/1934
